### ISSUE TITLE
ValueError: Failed to download data for symbol USDT_BTC after 5 attempts.

### ISSUE THREAD

**Issue by PyPatel** [enigmampc/catalyst-docs#3] opened 2017-08-27 13:09 UTC
I was testing the installation of Enigma Catalyst but this happened at the final stage...

Does it have something to do with Python 2.7 version or GDAX API?

**Error in Nutshell:**
2 Main errors: 

1. HTTPError: HTTP Error 403: Forbidden
2. ValueError: Failed to download data for symbol USDT_BTC after 5 attempts.

**Actual Error Message:**
` (catalyst-venv) C:\Users\Harsh Patel\Desktop\Data Science>catalyst run -f buy_and_hodl.py --start 2015-3-1 --end 2017-7-31 --capital-base 100000 -o bah.pickle
[2017-08-27 12:47:52.282000] INFO: Loader: Loading benchmark data for 'USDT_BTC' from 2015-02-28 00:00:00+00:00 to 2017-08-25 00:00:00+00:00
[2017-08-27 12:47:52.284000] INFO: Loader: Cache at C:\Users\Harsh Patel/.catalyst\data\USDT_BTC_benchmark.csv does not have data from 2015-03-01 00:00:00+00:00 to 2017-08-25 00:00:00+00:00.1`

`[2017-08-27 12:47:52.284000] INFO: Loader: Downloading benchmark data for 'USDT_BTC' from 2015-02-28 00:00:00+00:00 to 2017-08-25 00:00:00+00:00
HTTPError: HTTP Error 403: Forbidden
[2017-08-27 12:48:09.070000] ERROR: catalyst.data.bundles.base: Exception raised fetching poloniex data. Retrying.
[2017-08-27 12:48:07.079000] ERROR: catalyst.data.bundles.base: Exception raised fetching poloniex data. Retrying.z
Traceback (most recent call last):
  File "c:\dev\anaconda\envs\catalyst-venv\lib\site-packages\catalyst\data\bundles\base.py", line 491, in _fetch_symbol_frame
    data_frequency,
  File "c:\dev\anaconda\envs\catalyst-venv\lib\site-packages\catalyst\data\bundles\poloniex.py", line 102, in fetch_raw_symbol_frame
    orient='records',
  File "c:\dev\anaconda\envs\catalyst-venv\lib\site-packages\pandas\io\json.py", line 251, in read_json
    encoding=encoding)
  File "c:\dev\anaconda\envs\catalyst-venv\lib\site-packages\pandas\io\common.py", line 238, in get_filepath_or_buffer
    req = _urlopen(str(filepath_or_buffer))
  File "c:\dev\anaconda\envs\catalyst-venv\lib\urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "c:\dev\anaconda\envs\catalyst-venv\lib\urllib2.py", line 435, in open
    response = meth(req, response)
  File "c:\dev\anaconda\envs\catalyst-venv\lib\urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "c:\dev\anaconda\envs\catalyst-venv\lib\urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "c:\dev\anaconda\envs\catalyst-venv\lib\urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "c:\dev\anaconda\envs\catalyst-venv\lib\urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
Traceback (most recent call last):
  File "c:\dev\anaconda\envs\catalyst-venv\lib\site-packages\catalyst\data\bundles\base.py", line 491, in _fetch_symbol_frame
    data_frequency,
  File "c:\dev\anaconda\envs\catalyst-venv\lib\site-packages\catalyst\data\bundles\poloniex.py", line 102, in fetch_raw_symbol_frame
    orient='records',
  File "c:\dev\anaconda\envs\catalyst-venv\lib\site-packages\pandas\io\json.py", line 251, in read_json
    encoding=encoding)
  File "c:\dev\anaconda\envs\catalyst-venv\lib\site-packages\pandas\io\common.py", line 238, in get_filepath_or_buffer
    req = _urlopen(str(filepath_or_buffer))
  File "c:\dev\anaconda\envs\catalyst-venv\lib\urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "c:\dev\anaconda\envs\catalyst-venv\lib\urllib2.py", line 435, in open
    response = meth(req, response)
  File "c:\dev\anaconda\envs\catalyst-venv\lib\urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "c:\dev\anaconda\envs\catalyst-venv\lib\urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "c:\dev\anaconda\envs\catalyst-venv\lib\urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "c:\dev\anaconda\envs\catalyst-venv\lib\urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 403: Forbidden
[2017-08-27 12:48:09.232000] ERROR: catalyst.data.bundles.base: Exception raised fetching poloniex data. Retrying.
Traceback (most recent call last):
  File "c:\dev\anaconda\envs\catalyst-venv\lib\site-packages\catalyst\data\bundles\base.py", line 491, in _fetch_symbol_frame
    data_frequency,
  File "c:\dev\anaconda\envs\catalyst-venv\lib\site-packages\catalyst\data\bundles\poloniex.py", line 102, in fetch_raw_symbol_frame
    orient='records',
  File "c:\dev\anaconda\envs\catalyst-venv\lib\site-packages\pandas\io\json.py", line 251, in read_json
    encoding=encoding)
  File "c:\dev\anaconda\envs\catalyst-venv\lib\site-packages\pandas\io\common.py", line 238, in get_filepath_or_buffer
    req = _urlopen(str(filepath_or_buffer))
  File "c:\dev\anaconda\envs\catalyst-venv\lib\urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "c:\dev\anaconda\envs\catalyst-venv\lib\urllib2.py", line 435, in open
    response = meth(req, response)
  File "c:\dev\anaconda\envs\catalyst-venv\lib\urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "c:\dev\anaconda\envs\catalyst-venv\lib\urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "c:\dev\anaconda\envs\catalyst-venv\lib\urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "c:\dev\anaconda\envs\catalyst-venv\lib\urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 403: Forbidden
[2017-08-27 12:48:09.395000] ERROR: catalyst.data.bundles.base: Exception raised fetching poloniex data. Retrying.
Traceback (most recent call last):
  File "c:\dev\anaconda\envs\catalyst-venv\lib\site-packages\catalyst\data\bundles\base.py", line 491, in _fetch_symbol_frame
    data_frequency,
  File "c:\dev\anaconda\envs\catalyst-venv\lib\site-packages\catalyst\data\bundles\poloniex.py", line 102, in fetch_raw_symbol_frame
    orient='records',
  File "c:\dev\anaconda\envs\catalyst-venv\lib\site-packages\pandas\io\json.py", line 251, in read_json
    encoding=encoding)
  File "c:\dev\anaconda\envs\catalyst-venv\lib\site-packages\pandas\io\common.py", line 238, in get_filepath_or_buffer
    req = _urlopen(str(filepath_or_buffer))
  File "c:\dev\anaconda\envs\catalyst-venv\lib\urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "c:\dev\anaconda\envs\catalyst-venv\lib\urllib2.py", line 435, in open
    response = meth(req, response)
  File "c:\dev\anaconda\envs\catalyst-venv\lib\urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "c:\dev\anaconda\envs\catalyst-venv\lib\urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "c:\dev\anaconda\envs\catalyst-venv\lib\urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "c:\dev\anaconda\envs\catalyst-venv\lib\urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 403: Forbidden
[2017-08-27 12:48:09.544000] ERROR: catalyst.data.bundles.base: Exception raised fetching poloniex data. Retrying.
Traceback (most recent call last):
  File "c:\dev\anaconda\envs\catalyst-venv\lib\site-packages\catalyst\data\bundles\base.py", line 491, in _fetch_symbol_frame
    data_frequency,
  File "c:\dev\anaconda\envs\catalyst-venv\lib\site-packages\catalyst\data\bundles\poloniex.py", line 102, in fetch_raw_symbol_frame
    orient='records',
  File "c:\dev\anaconda\envs\catalyst-venv\lib\site-packages\pandas\io\json.py", line 251, in read_json
    encoding=encoding)
  File "c:\dev\anaconda\envs\catalyst-venv\lib\site-packages\pandas\io\common.py", line 238, in get_filepath_or_buffer
    req = _urlopen(str(filepath_or_buffer))
  File "c:\dev\anaconda\envs\catalyst-venv\lib\urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "c:\dev\anaconda\envs\catalyst-venv\lib\urllib2.py", line 435, in open
    response = meth(req, response)
  File "c:\dev\anaconda\envs\catalyst-venv\lib\urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "c:\dev\anaconda\envs\catalyst-venv\lib\urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "c:\dev\anaconda\envs\catalyst-venv\lib\urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "c:\dev\anaconda\envs\catalyst-venv\lib\urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "c:\dev\anaconda\envs\catalyst-venv\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\dev\anaconda\envs\catalyst-venv\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\dev\Anaconda\envs\catalyst-venv\Scripts\catalyst.exe\__main__.py", line 9, in <module>
  File "c:\dev\anaconda\envs\catalyst-venv\lib\site-packages\click\core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "c:\dev\anaconda\envs\catalyst-venv\lib\site-packages\click\core.py", line 697, in main
    rv = self.invoke(ctx)
  File "c:\dev\anaconda\envs\catalyst-venv\lib\site-packages\click\core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\dev\anaconda\envs\catalyst-venv\lib\site-packages\click\core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\dev\anaconda\envs\catalyst-venv\lib\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "c:\dev\anaconda\envs\catalyst-venv\lib\site-packages\catalyst\__main__.py", line 97, in _
    return f(*args, **kwargs)
  File "c:\dev\anaconda\envs\catalyst-venv\lib\site-packages\click\decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "c:\dev\anaconda\envs\catalyst-venv\lib\site-packages\catalyst\__main__.py", line 240, in run
    environ=os.environ,
  File "c:\dev\anaconda\envs\catalyst-venv\lib\site-packages\catalyst\utils\run_algo.py", line 197, in _run
    env, data = get_trading_env_and_data(bundles)
  File "c:\dev\anaconda\envs\catalyst-venv\lib\site-packages\catalyst\utils\run_algo.py", line 156, in get_trading_env_and_data
    environ=environ,
  File "c:\dev\anaconda\envs\catalyst-venv\lib\site-packages\catalyst\finance\trading.py", line 99, in __init__
    self.bm_symbol,
  File "c:\dev\anaconda\envs\catalyst-venv\lib\site-packages\catalyst\data\loader.py", line 135, in load_crypto_market_data
    environ,
  File "c:\dev\anaconda\envs\catalyst-venv\lib\site-packages\catalyst\data\loader.py", line 287, in ensure_crypto_benchmark_data
    'daily',
  File "c:\dev\anaconda\envs\catalyst-venv\lib\site-packages\catalyst\data\bundles\base.py", line 518, in _fetch_symbol_frame
    n=retries,
ValueError: Failed to download data for symbol USDT_BTC after 5 attempts. `

**Comment by lacabra** [comment] 2017-08-27 15:00
@PyPatel Thanks for reporting this issue. We have observed this issue from two other users that are located outside the United States, so I am guessing you are also outside the US. The problem is that we rely on a online service to download benchmark data for USD-BTC that behaves differently whether you access it from inside or outside the United States. I have been meaning to address this issue, and I plan on working on it tomorrow and release a new version that overcomes this limitation. Stay tunned. 

Also for future reference, please report issues regarding catalyst against the main repository at https://github.com/enigmampc/catalyst instead of this one that holds the documentation.

Thank you.

**Comment by PyPatel** [comment] 2017-08-27 15:26
I am accessing it from **India**. So It's issues with GDAX, then I can replace it with data of Bitfinex.

**Comment by lacabra** [comment] 2017-08-29 14:21
@PyPatel this issue has been resolved in commit [16f9ab](https://github.com/enigmampc/catalyst/commit/16f9ab3ba52ed4b6cf1c4c96e3593443ee81a1d6), which is part of 0.1.dev9 release. Please upgrade `pip install engima-catalyst --upgrade` to resolve your issue. Thanks again for reporting.

**Closed by lacabra** 2017-08-29 14:21 UTC

**Comment by PyPatel** [comment] 2017-08-29 18:34
Typo:  ` pip install enigma-catalyst --upgrade`
